/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import javax.swing.JButton;

/**
 *
 * @author Acer
 */
import viewConsole.Aplikasi;
import Model.BerkasLamaran;
import Model.Lowongan;
import Model.Orang;
import Model.Pelamar;
import Model.Perusahaan;
import java.awt.event.ActionListener;
public class MenuAwal extends javax.swing.JFrame {

    /**
     * Creates new form MenuAwal
     */
    public MenuAwal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labelAdaLoker = new javax.swing.JLabel();
        labelPerusahaan = new javax.swing.JLabel();
        labelPelamar = new javax.swing.JLabel();
        labelTmbhPerusahaan = new javax.swing.JLabel();
        btnPerusahaan = new javax.swing.JButton();
        btnPelamar = new javax.swing.JButton();
        btnTmbhPerusahaan = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        labelAdaLoker.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        labelAdaLoker.setText("ADALOKER");

        labelPerusahaan.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelPerusahaan.setText("Perusahaan");

        labelPelamar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelPelamar.setText("Pelamar");

        labelTmbhPerusahaan.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelTmbhPerusahaan.setText("Tambah Perusahaan");

        btnPerusahaan.setText("->");

        btnPelamar.setText("->");
        btnPelamar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPelamarActionPerformed(evt);
            }
        });

        btnTmbhPerusahaan.setText("->");

        jLabel1.setText("Aplikasi DAta LOwongan KERja");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelPerusahaan)
                    .addComponent(labelPelamar)
                    .addComponent(labelTmbhPerusahaan))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPelamar)
                    .addComponent(btnPerusahaan)
                    .addComponent(labelAdaLoker)
                    .addComponent(btnTmbhPerusahaan))
                .addContainerGap(131, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(113, 113, 113))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(labelAdaLoker)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPerusahaan)
                    .addComponent(btnPerusahaan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPelamar)
                    .addComponent(btnPelamar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTmbhPerusahaan)
                    .addComponent(labelTmbhPerusahaan))
                .addGap(0, 120, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPelamarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPelamarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPelamarActionPerformed

    /**
     * @param args the command line arguments
     */

    public JButton getBtnPelamar() {
        return btnPelamar;
    }

    public JButton getBtnPerusahaan() {
        return btnPerusahaan;
    }

    public JButton getBtnTmbhPerusahaan() {
        return btnTmbhPerusahaan;
    }
    
    public void addActionListener (ActionListener e){
        btnPelamar.addActionListener(e);
        btnPerusahaan.addActionListener(e);
        btnTmbhPerusahaan.addActionListener(e);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPelamar;
    private javax.swing.JButton btnPerusahaan;
    private javax.swing.JButton btnTmbhPerusahaan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelAdaLoker;
    private javax.swing.JLabel labelPelamar;
    private javax.swing.JLabel labelPerusahaan;
    private javax.swing.JLabel labelTmbhPerusahaan;
    // End of variables declaration//GEN-END:variables
}
